### ISSUE TITLE
Certain 8-bit signed multipliers use unsigned inputs/output

### ISSUE THREAD

**Issue by NRodion** [mrazekv/approxlib#4]
Hello,

C-files for 1L2J, 1L2L and 1L2N 8-bit signed multipliers in MAE vs power set have uint8_t inputs and uint16_t outputs, which leads to incorrect results when values <0 are passed to them. Every other C-file has int8_t and int16_t and works completely fine. Looks like, that simply changing output and O to int16_t and inputs to int8_t, fixes the issue.

**Comment by mrazekv** [comment]
Thank you for the notice and fix. Unfortunately, we are not able to regenerate all circuits now
